name: build
on:
  push:

jobs:
  lint:
    name: "Lint repo"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: install precommit
        run: |
          python -m pip install -U pip setuptools
          python -m pip install pre-commit
      - name: run pre-commit
        run: pre-commit run -a
  self-check:
    name: "Self-Check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: install from source
        run: |
          python -m pip install -U pip setuptools
          python -m pip install .
      - name: run on own workflow
        run: check-jsonschema  --schemafile "https://json.schemastore.org/github-workflow" .github/workflows/build.yaml
