name: Publish Test PyPI Release

on:
  workflow_dispatch:
    inputs:
      devNumber:
        required: false
        type: number
        description: 'The number to use as a ".devN" suffix. Defaults to 1.'

  push:
    tags: ["*"]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: publish-testpypi
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - run: python -m pip install build

      - name: Set dev version prior to upload (auto)
        if: ${{ github.event.inputs.devNumber == '' }}
        run: python ./scripts/set-dev-version.py

      - name: Set dev version prior to upload (workflow_dispatch)
        if: ${{ github.event.inputs.devNumber != '' }}
        run: python ./scripts/set-dev-version.py -n ${{ github.event.inputs.devNumber }}

      - run: python -m build .

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository_url: https://test.pypi.org/legacy/
