name: Publish PyPI Release

on:
  release:
    types: [published]

jobs:
  build-dists:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - run: python -m pip install build twine

      - name: Build Dists
        run: python -m build .

      - name: Check Dists (twine)
        run: twine check dist/*

      - uses: actions/upload-artifact@v3
        with:
          name: packages
          path: dist/*

  publish:
    needs: [build-dists]
    runs-on: ubuntu-latest
    environment: publish-testpypi
    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: packages
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
